spring:
  jackson:
    time-zone: Asia/Shanghai
  cloud:
    nacos:
      discovery:
        metadata:
          context-path: ${spring.application.name}

management:
  metrics:
    tags:
      application: ${spring.application.name}
      #app-version: '@project.version@'
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: dev


---
spring:
  config:
    activate:
      on-profile: uat
