server:
  port: 8080
  servlet:
    context-path: /admin

platform:
  resilience:
    isHotWarmModel: false

spring:
# 允许bean定义覆盖
#  main:
#    allow-bean-definition-overriding: true
  application:
    name: example-service
    version: '@project.version@'
  profiles:
    active: '@profiles.active@'
    include: web

---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: uat
server:
  port: 8980

