server:
  port: 8080
  servlet:
    context-path: /admin

platform:
  resilience:
    isHotWarmModel: false

spring:
  application:
    name: example-service
    version: '@project.version@'
  profiles:
    active: '@profiles.active@'
    include: core,web,nacos

---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: uat
server:
  port: 8980

